# Generated by Django 3.2.25 on 2025-04-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elasticsearch_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
