# Generated by Django 3.2.25 on 2025-03-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextSearchTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'textsearch_tags',
            },
        ),
        migrations.CreateModel(
            name='TextSearchProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('sku', models.CharField(max_length=100)),
                ('thumbnail', models.URLField(max_length=1000)),
                ('tags', models.ManyToManyField(to='textsearch.TextSearchTags')),
            ],
            options={
                'db_table': 'textsearch_Product',
            },
        ),
    ]
