# Generated by Django 3.2.25 on 2025-03-28 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Female'), ('Male', 'Female')], max_length=100)),
            ],
        ),
    ]
