# Generated by Django 3.2.25 on 2025-03-28 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageresizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100),
        ),
    ]
