# Generated by Django 3.2.25 on 2025-03-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageresizer', '0002_auto_20250328_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='images/')),
                ('thumbnail_small', models.ImageField(blank=True, null=True, upload_to='images/thumbnaila')),
                ('thumbnail_medium', models.ImageField(blank=True, null=True, upload_to='images/thumbnaila')),
                ('thumbnail_large', models.ImageField(blank=True, null=True, upload_to='images/thumbnaila')),
            ],
            options={
                'db_table': 'imagemodel',
            },
        ),
    ]
