# Generated by Django 3.2.25 on 2025-02-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=255)),
                ('speed', models.IntegerField(default=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
