# Generated by Django 3.2.25 on 2025-03-09 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20250309_0832'),
        ('home', '0010_auto_20250309_0852'),
    ]

    operations = [
    ]
