# Generated by Django 3.2.25 on 2025-03-09 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_merge_0010_auto_20250309_0832_0010_auto_20250309_0852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['person_name'], 'verbose_name': 'Persones', 'verbose_name_plural': 'Persones'},
        ),
        migrations.AlterIndexTogether(
            name='skills',
            index_together={('skill_name', 'is_soft_skill')},
        ),
    ]
