# Generated by Django 5.2 on 2025-05-01 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_auto_20250317_0800"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="skills",
            new_name="skills_skill_n_ee72f2_idx",
            old_fields=("skill_name", "is_soft_skill"),
        ),
    ]
