# Generated by Django 3.2.25 on 2025-03-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmp_id', models.CharField(max_length=100, unique=True)),
                ('store_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'MODELNAMEs',
            },
        ),
    ]
