# Generated by Django 3.2.25 on 2025-03-22 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djmiddleware', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'Store', 'verbose_name_plural': 'Stores'},
        ),
    ]
